apiVersion: v1
data:
  # See agent/start-with-appd.sh
  APPDYNAMICS_AGENT_VERSION: "20.7.0.2292"
  APPDYNAMICS_AGENT_CONFIG: ""
  #APP_ENTRY_POINT: python /app/app/app.py
  APPD_PROXY_CONTROL_PATH: ""

  # See https://docs.appdynamics.com/display/PRO45/Python+Agent+Settings
  APPD_CONTROLLER_HOST: "ec2-54-191-211-161.us-west-2.compute.amazonaws.com"
  APPD_CONTROLLER_PORT: "8090"
  APPD_ACCOUNT_NAME: "customer1"
  APPD_APP_NAME: "python-demo"
          
kind: ConfigMap
metadata:
  name: agent-startup-config
